apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-deployment
  labels:
    app: articles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles
  template:
    metadata:
      labels:
        app: articles
    spec:
      containers:
      - name: articles
        image: streamio.azurecr.io/streamio-backend_articles:v1
        env:
          - name: ARTICLEFEEDHOST
            value: 10.0.188.79:3000
          - name: REVIEWFEEDHOST
            value: 10.0.211.234:4001
          - name: PORT
            value: "4005"
        ports:
        - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: articles-service
spec:
  selector:
    app: articles
  ports:
    - port: 3000
      targetPort: 3000